version: '3.8'
services:
  demo:
    container_name: demo
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digitusapp
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dev_pma
    restart: always
    environment:
      PMA_HOST: demo
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8183:80"